### ISSUE TITLE
Can't seem to run this

### ISSUE THREAD

**Issue by ChikyuTenshi** [kujan/NGU-scripts#31]
Sorry if this is such a noob question but I followed everything listed but I can't seem to run this? tried running all .py files but the command prompt just closes after few seconds

any help will be appreciated

**Comment by kujan** [comment]
Open a command prompt (you can type ``cmd`` in the address bar in explorer to open a prompt  in the current directory) and run the script from there by invoking ``python main.py`` or ``python3 main.py``. If it crashes the window doesn't close and you can share the error message.

**Comment by kujan** [comment]
Try again while using the default theme.

**Comment by ChikyuTenshi** [comment]
I apologize for that and it seems to be working now, although the OCR is getting stuck detecting XP and PP (I guess I'm too low of a level to use the script since I don't even know what PP is) but I will give it a go once I'm a bit higher level

Thanks for the help Kujan~
